# Generated by Django 3.2.16 on 2024-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241010_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тега'),
        ),
    ]
