# Generated by Django 4.2.16 on 2024-10-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241010_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='title',
        ),
    ]
